version: '3'
services:
  api:
    restart: 'always'
    command: './run.sh'
    build:
      context: backend
      dockerfile: Dockerfile-dev
    volumes:
      - ./backend:/app
    environment:
      - ENVIRONMENT=dev
      - DEBUG=1
      - ADMIN_EMAIL=admin@amts.com
      - ADMIN_PASSWORD=12345
      - SMTP_PASSWORD=""
      - HOST=amts.mmelo.me
      - DATABASE_URI=mysql+pymysql://amts:supersecret@mariadb:3306/db
      - DATABASE_PASSWORD=supersecret
      - DATABASE_USER=amts
    depends_on:
      - mariadb

  nginx:
    image: nginx
    restart: 'always'
    volumes:
      - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    command: ["npm", "start"]
    restart: 'always'
    volumes:
      - ./frontend:/usr/src/app

  mariadb:
    image: bitnami/mariadb
    restart: 'always'
    environment:
      - MARIADB_ROOT_PASSWORD=supersecret
      - MARIADB_USER=amts
      - MARIADB_PASSWORD=supersecret
      - MARIADB_DATABASE=db
